Repository Razvan48/Proiect-Metode-de-Dezvoltare-Software-MDS, pull requests merged in 2024-04, with the labels that each got.

#7 Input handler
  Apocalypse/source/Game/Game.cpp
  Apocalypse/source/Input/InputHandler.cpp
  Apocalypse/source/Input/InputHandler.h
  Apocalypse/source/WindowManager/WindowManager.cpp
  Apocalypse/source/WindowManager/WindowManager.h
  premake5.lua
Labels: integration

#9 Fixed 👍
  Apocalypse/source/Entity/Player/Player.cpp
Labels: dev-bug

#11 Character Rotation Visual Bug
  Apocalypse/source/Entity/Player/Player.cpp
Labels: visual-bug

#13 Fixed player running
  Apocalypse/source/Entity/AnimatedEntity.cpp
  Apocalypse/source/Entity/Player/Player.cpp
Labels: visual-bug

#14 HUD Manager
  Apocalypse/source/Entity/Player/Player.cpp
  Apocalypse/source/Game/Game.cpp
  Apocalypse/source/HUD/HUDManager.cpp
  Apocalypse/source/HUD/HUDManager.h
  Apocalypse/textures/hud/blue.png
  Apocalypse/textures/hud/green.png
  Apocalypse/textures/hud/red.png
Labels: integration

#16 Sound engine
  .gitignore
  Apocalypse/resources/sounds/running.mp3
  Apocalypse/resources/sounds/walking.mp3
  Apocalypse/source/Entity/Player/Player.cpp
  Apocalypse/source/Game/Game.cpp
  Apocalypse/source/ResourceManager/ResourceManager.cpp
  Apocalypse/source/ResourceManager/ResourceManager.h
  Apocalypse/source/SoundManager/SoundManager.cpp
  Apocalypse/source/SoundManager/SoundManager.h
  premake5.lua
  vendor/fmod/include/fmod.cs
  vendor/fmod/include/fmod.h
  vendor/fmod/include/fmod.hpp
  vendor/fmod/include/fmod_codec.h
  vendor/fmod/include/fmod_common.h
  vendor/fmod/include/fmod_dsp.cs
  vendor/fmod/include/fmod_dsp.h
  vendor/fmod/include/fmod_dsp_effects.h
  vendor/fmod/include/fmod_errors.cs
  vendor/fmod/include/fmod_errors.h
  vendor/fmod/include/fmod_output.h
  vendor/fmod/lib/arm64/fmod.dll
  vendor/fmod/lib/arm64/fmodL.dll
  vendor/fmod/lib/arm64/fmodL_vc.lib
  vendor/fmod/lib/arm64/fmod_vc.lib
  vendor/fmod/lib/x64/fmod.dll
  vendor/fmod/lib/x64/fmodL.dll
  vendor/fmod/lib/x64/fmodL_vc.lib
  vendor/fmod/lib/x64/fmod_vc.lib
  vendor/fmod/lib/x86/fmod.dll
  vendor/fmod/lib/x86/fmodL.dll
  vendor/fmod/lib/x86/fmodL_vc.lib
  vendor/fmod/lib/x86/fmod_vc.lib
  vendor/fmod/lib/x86/libfmod.a
  vendor/fmod/lib/x86/libfmodL.a
Labels: integration
